name: Setup uv
description: Set up your GitHub Actions workflow with a specific version of uv
author: Yasser Tahiri
inputs:
  uv-preview:
    description: Allow to install prerelease versions of uv.
    required: false
    default: "false"
  uv-version:
    description: uv version to use, if version is not provided then latest stable version will be used
    required: false
  uv-venv:
    description: uv venv name to create, if not provided then .venv will be used
    required: false
    default: '.venv'
runs:
  using: node20
  main: dist/index.js
branding:
  icon: package
  color: purple